### ISSUE TITLE
IE11 compatibility issue

### ISSUE THREAD

**Issue by amandacgross** [enbifa/jquery.skeleton.loader#2]
When creating a basic skeleton on IE I get:

`TypeError: Object doesn't support property or method 'remove'`
`at Anonymous function (eval code:337:29)`

I believe because [.remove() is not available for IE](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Browser_compatibility)

**Comment by enbifa** [comment]
Fix added in the new release 1.2!
