### ISSUE TITLE
Expose a function to disable the loader after sometime 

### ISSUE THREAD

**Issue by Yogeeshvh** [enbifa/jquery.skeleton.loader#3]
I am using Firebase, where I subscribed to event and I want to disable the loader inside event callback, but currently it's not possible. Please expose a function to disable the loader

**Comment by enbifa** [comment]
Hi @Yogeeshvh I published a new version with the method exposed. you just have to use it like this

var instance = $('#myDIV').scheletrone('stopLoader');

thanks for your note ;)
